name: deploy web2metaid-server

on:
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'dist/**'
      - 'package.json'
      - 'ecosystem.config.js'
      - '.env'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v3
        with:
          path: 'web2metaid-server'

      - name: 打印 REMOTE_HOST
        run: 
          echo "${{secrets.REMOTE_HOST}}"  &&  echo "${{secrets.REMOTE_SERVER_DIR}}" 
 
      - name: 设置 id_rsa
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SHOWPAY_MACMINI_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{secrets.REMOTE_HOST}} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: 将远程服务器的对应目录下所有文件及文件夹删除
        run: | # type-room/server
          ssh root@${{secrets.REMOTE_HOST}} "
            cd ${{secrets.REMOTE_SERVER_DIR}};
            pm2 kill;
            rm -rf ./*;
          "

      - name: 将项目复制到远程服务器对应目录
        run: |
          rsync -avz --exclude=".git" --exclude="node_modules" web2metaid-server/ root@${{secrets.REMOTE_HOST}}:${{secrets.REMOTE_SERVER_DIR}}
          ls -a

      - name: 启动 pm2
        run: |
          ssh root@${{secrets.REMOTE_HOST}} "
            cd  ${{secrets.REMOTE_SERVER_DIR}};
            ls -a;
            apt-get install -y npm;
            npm install -g pnpm;
            pnpm install;
            pnpm prod;
          "

      - name: 删除 id_rsa
        run: rm -rf ~/.ssh/id_rsa
